# Generated by Django 4.2.4 on 2023-08-15 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "category_code",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="__main__.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("coupon_code", models.CharField(max_length=32)),
                ("campaign_type", models.SmallIntegerField()),
                ("discount_type", models.SmallIntegerField()),
                ("discount_value", models.SmallIntegerField()),
                ("min_order_value", models.SmallIntegerField()),
                ("max_discount", models.SmallIntegerField()),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=128)),
                ("phone_number", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("text", models.TextField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CustomerAddressHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "customer_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.customeraddress",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LibraryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("sp", models.SmallIntegerField()),
                ("mrp", models.SmallIntegerField()),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("state", models.SmallIntegerField(default=1)),
                (
                    "coupon_discount_amount",
                    models.SmallIntegerField(default=None, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.customer",
                    ),
                ),
                (
                    "customer_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.customeraddresshistory",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=256)),
                ("image_urls", models.TextField()),
                (
                    "categories",
                    models.ManyToManyField(default=None, to="__main__.category"),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=128)),
                ("phone_number", models.BigIntegerField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("mrp", models.SmallIntegerField()),
                ("sp", models.SmallIntegerField()),
                ("in_stock", models.SmallIntegerField()),
                (
                    "detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.productdetail",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="__main__.store"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StoreProductPriceChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("sp", models.SmallIntegerField()),
                ("mrp", models.SmallIntegerField()),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.storeproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StoreCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.coupon",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="__main__.store"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="store",
            name="coupons",
            field=models.ManyToManyField(
                through="__main__.StoreCoupon", to="__main__.coupon"
            ),
        ),
        migrations.CreateModel(
            name="OrderSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_coupon",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.coupon",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="__main__.order"
                    ),
                ),
                (
                    "store_product_price_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.storeproductpricechangelog",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="order",
            name="order_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="__main__.ordersession"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="__main__.store"
            ),
        ),
        migrations.CreateModel(
            name="LibraryProductPriceChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("sp", models.SmallIntegerField()),
                ("mrp", models.SmallIntegerField()),
                (
                    "library_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.libraryproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="libraryproduct",
            name="detail",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="__main__.productdetail"
            ),
        ),
        migrations.AddField(
            model_name="libraryproduct",
            name="parent_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="__main__.libraryproduct",
            ),
        ),
        migrations.CreateModel(
            name="CustomerCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.coupon",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__main__.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="coupons",
            field=models.ManyToManyField(
                through="__main__.CustomerCoupon", to="__main__.coupon"
            ),
        ),
    ]
