# Generated by Django 4.2.4 on 2023-08-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("__main__", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="version",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="quantity",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="version",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_location",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="__main__.customeraddresshistory",
            ),
        ),
    ]
