# Generated by Django 4.2.4 on 2023-08-15 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("__main__", "0002_order_version_orderproduct_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="__main__.ordersession",
            ),
        ),
    ]
