# Generated by Django 4.2.4 on 2023-08-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("__main__", "0003_alter_order_order_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product_total",
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
